# This file was generated by GoReleaser. DO NOT EDIT.
class CfContext < Formula
  desc ""
  homepage ""
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mrombout/cf-context/releases/download/v0.1/cf-context_0.1_darwin_amd64.tar.gz"
    sha256 "ec99354185c918ea771cd67f29580fa1dc9cf839a573efaa3f4379cbb1f524ff"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mrombout/cf-context/releases/download/v0.1/cf-context_0.1_linux_amd64.tar.gz"
      sha256 "fcd14abdc3e606c625a7b2994e23fae58b1b7017531610f6843ffd6c10c9a9b2"
    end
  end

  def install
    bin.install "cf-context"
  end
end
