# This file was generated by GoReleaser. DO NOT EDIT.
class CfContext < Formula
  desc ""
  homepage ""
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mrombout/cf-context/releases/download/v0.1/cf-context_0.1_darwin_amd64.tar.gz"
    sha256 "b7e6f49e2111fd5ddfc77959dc4c216cd38240fb81d4cb535192fab854fce7c1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mrombout/cf-context/releases/download/v0.1/cf-context_0.1_linux_amd64.tar.gz"
      sha256 "f5186025b9270f222f2f4c1e827a841e8428aaa43fe5f3215669e65831f21fec"
    end
  end

  def install
    bin.install "cf-context"
  end
end
